# Site settings
title: Dermanova
tagline: Frumusete fara durere
email: sumataleb@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Clinica de dermato-cosmetologie Dermanova, în care prioritatea o reprezintă
  atât calitatea actului medical cât şi relația medic–pacient, bazată pe
  încredere şi confidențialitate, pune la dispoziția dumneavoastră servicii
  medicale la cele mai înalte standarde.
baseurl: "/dermanova" # the subpath of your site, e.g. /blog
url: "https://bogdansoare.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - octopress-autoprefixer
